language: "node_js"
sudo: false

node_js:
  - "8"
  - "10"

notifications:
  email:
    on_success: never
    on_failure: never

before_script:
  - npm install standard
  - standard

script:
  - npm install istanbul
  - istanbul cover test.js

after_success:
  - npm install coveralls
  - cat ./coverage/lcov.info | coveralls
